import Footer from './components/Footer'
import NavBar from './components/NavBar'
import {Toaster} from 'react-hot-toast'
import './globals.css'
// import { Inter } from 'next/font/google'

import { Roboto } from 'next/font/google'
import NewFooter from './components/NewFooter'
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {/* <Header/> */}
        {/* <Nav/> */}
        <NavBar/>
        <Toaster position='top-center'/>
        {children}
        <Footer/>
        {/* <NewFooter/> */}
      </body>
    </html>
  )
}
