
import Footer from './components/Footer'
import NavBar from './components/NavBar'
import { UserProvider } from './context/UserContext'
import './globals.css'
import { Toaster } from "react-hot-toast";

// import { Inter } from 'next/font/google'

import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body className={roboto.className}>
        <UserProvider>
          <NavBar/>
          <Toaster/>
          {children}
          <Footer/>
        </UserProvider>
      </body>
    </html>
  )
}
